In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

In [4]:
a = pd.read_csv("/content/drive/MyDrive/Data Analyst/Momo Hoàn tiền/Loyalty Points.csv")
b = pd.read_csv("/content/drive/MyDrive/Data Analyst/Momo Hoàn tiền/Loyalty benefits.csv")
c = pd.read_csv("/content/drive/MyDrive/Data Analyst/Momo Hoàn tiền/Merchant.csv")
d = pd.read_csv("/content/drive/MyDrive/Data Analyst/Momo Hoàn tiền/Transactions.csv")

In [ ]:
#coi sơ qua data
a.info()
a.duplicated().sum()
a.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Service Group            6 non-null      object
 1   Point Mechanism          6 non-null      object
 2   Maximum Point Per Trans  6 non-null      object
dtypes: object(3)
memory usage: 272.0+ bytes

Service Group              0
Point Mechanism            0
Maximum Point Per Trans    0
dtype: int64

In [ ]:
b.info()
b.duplicated().sum()
b.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Class ID   13 non-null     int64
 1   Group      13 non-null     object
 2   %cashback  13 non-null     int64
dtypes: int64(2), object(1)
memory usage: 440.0+ bytes

Class ID     0
Group        0
%cashback    0
dtype: int64

In [ ]:
c.info()
c.duplicated().sum()
c.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218 entries, 0 to 217
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ServiceID      218 non-null    object
 1   Service Group  218 non-null    object
 2   Merchant       218 non-null    object
 3   MerchantID     218 non-null    int64
dtypes: int64(1), object(3)
memory usage: 6.9+ KB

ServiceID        0
Service Group    0
Merchant         0
MerchantID       0
dtype: int64

In [5]:
d.info()
d.duplicated().sum() #có 3585 duplicate
d.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52760 entries, 0 to 52759
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   DATE                  52760 non-null  object
 1   Order_id              52760 non-null  int64
 2   NEWVERTICAL_Merchant  52760 non-null  object
 3   MerchantID            52760 non-null  int64
 4   User_id               52760 non-null  int64
 5   GMV                   52760 non-null  int64
 6   Service Group         52760 non-null  object
dtypes: int64(4), object(3)
memory usage: 2.8+ MB

DATE                    0
Order_id                0
NEWVERTICAL_Merchant    0
MerchantID              0
User_id                 0
GMV                     0
Service Group           0
dtype: int64

In [6]:
d = d.drop_duplicates().reset_index(drop = True)

In [7]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49175 entries, 0 to 49174
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   DATE                  49175 non-null  object
 1   Order_id              49175 non-null  int64
 2   NEWVERTICAL_Merchant  49175 non-null  object
 3   MerchantID            49175 non-null  int64
 4   User_id               49175 non-null  int64
 5   GMV                   49175 non-null  int64
 6   Service Group         49175 non-null  object
dtypes: int64(4), object(3)
memory usage: 2.6+ MB

In [8]:
a = a.to_csv('LoyaltyPoints.csv',index = False, header=True) # lưu file lại dưới định dạng csv
b = b.to_csv('LoyaltyBenefits.csv',index = False, header=True) # lưu file lại dưới định dạng csv
c = c.to_csv('Merchant.csv',index = False, header=True) # lưu file lại dưới định dạng csv
d = d.to_csv('Transactions.csv',index = False, header=True) # lưu file lại dưới định dạng csv